server:
  port: 8080

spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 3
      idle-timeout: 600000
    url: jdbc:h2:tcp://localhost/~/mydb
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

auth:
  white-list:
    - /swagger-ui/**
    - /v1/health
    - /v1/auth/**
    - /v2/api-docs
    - /v3/api-docs
    - /configuration/**
    - /swagger*/**
    - /webjars/**
    - /v1/**
    - /h2-console/**
  cors:
    allowed-origin:
      - http://localhost:8080
