spring:
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 3
      idle-timeout: 600000
    url: jdbc:h2:tcp://localhost/~/mydb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
auth:
  white-list:
    - /swagger-ui/**
    - /v1/health
    - /v1/auth/**
    - /v2/api-docs
    - /configuration/**
    - /swagger*/**
    - /webjars/**
    - /v1/auth/*
cors:
  allowed-origin:
    - http://localhost:8080
server:
  port: 8080